baseURL: 'https://essgeelabs.com/'
languageCode: en-us
title: Ess Gee Labs
theme: PaperMod
paginate: 5
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
menu:
  main:
    - identifier: personalwebsite
      name: personal website
      url: 'https://www.sachinganpat.com'
      weight: 10
    - identifier: businesswebsite
      name: business website
      url: 'https://www.interxect.com'
      weight: 11
    - identifier: categories
      name: categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30
    - identifier: search
      name: search
      url: /search/
      weight: 40
params:
  title: EssGeeLabs
  env: production
  description: Cool site for cool stuff.
  keywords:
    - Blog
    - Projects
    - Technology
    - DevOps
  author: Sachin Ganpat
  DateFormat: 'January 2, 2006'
  defaultTheme: light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  homeInfoParams:
    Title: "Welcome to the homepage of Ess Gee Labs"
    Content: > 
      
      - Here I'll be posting content on the things I do in the areas of: 

      - &nbsp;&nbsp;• DevOps, DevSecOps and CyberSecurity

      - &nbsp;&nbsp;• Network and Infrastructure Architectures

      - &nbsp;&nbsp;• Machine Learning and Intelligence Augmentation

      - &nbsp;&nbsp;• Electronics and The Internet of Things

      - &nbsp;&nbsp;• Web Development and Programming in Python

      - &nbsp;&nbsp;• And whatever else that piques my interest

  socialIcons:
    - name: twitter
      url: 'https://twitter.com/sachin_ganpat'
    - name: linkedin
      url: 'https://www.linkedin.com/in/sganpat/'
    - name: github
      url: 'https://github.com/essgeelabs'
    - name: RsS
      url: 'index.xml'
  assets:
    favicon: /favicon.ico
    favicon16x16: /favicon-16x16.png
    favicon32x32: /favicon-32x32.png
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content
      - author
  cover:
    # hidden: false 
    hiddenInList: true 
    hiddenInSingle: false 


taxonomies:
  category: categories
  tag: tags


privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

minify:
  disableXML: true

